/////////////////////////////////////////////////////////////////////////////
// Purpose:   Collect and generate FFI export symbol files
// Author:    Ralph Walden
// Copyright: Copyright (c) 2026 KeyWorks Software (Ralph Walden)
// License:   Apache License -- see LICENSE
/////////////////////////////////////////////////////////////////////////////

#include "exports_gen.h"

#include "file_writer.h"

#include <algorithm>
#include <format>
#include <iostream>
#include <locale>
#include <tuple>

namespace fs = std::filesystem;

std::vector<std::string> CollectExportSymbols(const ParsedFFI& ffi_data)
{
    std::vector<std::string> symbols;

    // Class methods — use the original C symbol name.
    for (const auto& class_info: ffi_data.classes)
    {
        for (const auto& method: class_info.methods)
        {
            if (!method.c_func_name.empty())
            {
                symbols.push_back(method.c_func_name);
            }
        }
    }

    // Event type exports (e.g., exp_wxEVT_BUTTON).
    for (const auto& event: ffi_data.events)
    {
        symbols.push_back(event.export_name);
    }

    // Key code exports (e.g., exp_wxK_BACK).
    for (const auto& key_code: ffi_data.keys)
    {
        symbols.push_back(key_code.export_name);
    }

    // Constants from kwx_defs.cpp and WXFFI_EXPORT in kwx_constants.h.
    for (const auto& constant: ffi_data.constants)
    {
        symbols.push_back(constant.export_name);
    }

    // Free functions from kwx_constants.h and kwx_classes.h.
    for (const auto& func: ffi_data.free_functions)
    {
        // Class-parser-sourced free functions have c_func_name set;
        // constants-parser-sourced ones only have method_name.
        if (!func.c_func_name.empty())
        {
            symbols.push_back(func.c_func_name);
        }
        else if (!func.method_name.empty())
        {
            symbols.push_back(func.method_name);
        }
    }

    // Sort and deduplicate for stable, deterministic output.
    std::ranges::sort(symbols);
    const auto [first, last] = std::ranges::unique(symbols);
    symbols.erase(first, last);

    return symbols;
}

void GenerateExportFiles(const ParsedFFI& ffi_data, const fs::path& out_dir)
{
    std::ignore = fs::create_directories(out_dir);
    const std::vector<std::string> symbols = CollectExportSymbols(ffi_data);

    size_t written = 0;

    // ---- Windows module-definition file (.def) ----
    {
        ConditionalFileWriter writer(out_dir / "kwxffi_exports.def");
        writer << "; Generated by kwxgen -- do not edit\n";
        writer << "EXPORTS\n";
        for (const auto& symbol: symbols)
        {
            writer << "    " << symbol << "\n";
        }
        if (writer.Flush())
        {
            ++written;
        }
    }

    // ---- Linux linker version script (.map) ----
    {
        ConditionalFileWriter writer(out_dir / "kwxffi_exports.map");
        writer << "/* Generated by kwxgen -- do not edit */\n";
        writer << "{\n";
        writer << "    global:\n";
        for (const auto& symbol: symbols)
        {
            writer << "        " << symbol << ";\n";
        }
        writer << "    local: *;\n";
        writer << "};\n";
        if (writer.Flush())
        {
            ++written;
        }
    }

    // ---- macOS exported symbols list (.exp) ----
    {
        ConditionalFileWriter writer(out_dir / "kwxffi_exports.exp");
        writer << "# Generated by kwxgen -- do not edit\n";
        for (const auto& symbol: symbols)
        {
            writer << "_" << symbol << "\n";
        }
        if (writer.Flush())
        {
            ++written;
        }
    }

    static const std::locale user_locale("");
    std::cerr << std::format(user_locale,
                             "Exports: {:L} symbols, {} of 3 files written to {}\n",
                             symbols.size(), written, out_dir.string());
}
