/////////////////////////////////////////////////////////////////////////////
// Purpose:   Common inline utilities shared across all kwxgen language emitters
// Author:    Ralph Walden
// Copyright: Copyright (c) 2026 KeyWorks Software (Ralph Walden)
// License:   Apache License -- see ../LICENSE
/////////////////////////////////////////////////////////////////////////////

#pragma once

// Common inline utilities shared across all kwxgen language emitters.
// Include this header in lang_*.cpp files only.

#include "../model.h"

#include <cctype>
#include <cstddef>
#include <ostream>
#include <string>
#include <string_view>

// Returns true if a FunctionDecl is well-formed (no comment artifacts, non-empty method name).
[[nodiscard]] inline bool IsValidFunction(const FunctionDecl& func)
{
    if (func.return_type.contains("//") || func.return_type.contains("/*") ||
        func.return_type.contains("*/"))
    {
        return false;
    }
    if (func.method_name.contains("//") || func.method_name.contains("/*"))
    {
        return false;
    }
    if (func.method_name.empty())
    {
        return false;
    }
    for (const auto& param: func.params)
    {
        if (param.raw_type.contains("//") || param.raw_type.contains("/*"))
        {
            return false;
        }
    }
    return true;
}

// Build the C exported function name: "wxButton_Create", or just method_name for free
// functions (class_name is empty).  Prefer the verbatim c_func_name captured by the parser
// when available (handles shortened prefixes like BitmapDataObject_Create).
inline std::string CFuncName(const FunctionDecl& func)
{
    if (!func.c_func_name.empty())
    {
        return func.c_func_name;
    }
    if (func.class_name.empty())
    {
        return func.method_name;
    }
    return func.class_name + "_" + func.method_name;
}

// Write the standard "do not edit" header comment to a generated file.
//   commentPrefix  — the single-line comment leader for the target language ("//", "#", "--")
//   extraNewline   — emit a second blank line after the header (Go/Rust/Julia style)
inline void WriteGeneratedHeader(std::ostream& output, std::string_view comment_prefix = "//",
                                 bool extra_newline = true)
{
    output << comment_prefix << " Code generated by kwxgen. DO NOT EDIT.\n";
    if (extra_newline)
    {
        output << "\n";
    }
}

// Lowercase an entire string: "TextCtrl" → "textctrl".
inline std::string ToLower(const std::string& text)
{
    std::string result;
    result.reserve(text.size());
    for (const char char_val: text)
    {
        result += static_cast<char>(std::tolower(static_cast<unsigned char>(char_val)));
    }
    return result;
}

// Convert CamelCase to snake_case: "SetDefault" → "set_default".
// Handles acronyms correctly: "GetHTML" → "get_html".
inline std::string ToSnakeCase(const std::string& name)
{
    std::string result;
    for (std::size_t i = 0; i < name.size(); ++i)
    {
        const char curr_char = name[i];
        if (std::isupper(static_cast<unsigned char>(curr_char)))
        {
            if (i > 0)
            {
                const char prev = name[i - 1];
                const bool prev_lower = std::islower(static_cast<unsigned char>(prev)) != 0;
                const bool next_lower = (i + 1 < name.size()) &&
                                        std::islower(static_cast<unsigned char>(name[i + 1])) != 0;
                if (prev_lower || (std::isupper(static_cast<unsigned char>(prev)) && next_lower))
                {
                    result += '_';
                }
            }
            result += static_cast<char>(std::tolower(static_cast<unsigned char>(curr_char)));
        }
        else
        {
            result += curr_char;
        }
    }
    return result;
}
